-- 연습문제

-- create a table
CREATE TABLE EMPLOYEE (
  EMP_ID INTEGER PRIMARY KEY,
  NAME TEXT NOT NULL,
  DEPT_ID INT,
  SALARY INT,
  BONUS INT
);

-- insert some values
INSERT INTO EMPLOYEE VALUES (101, '김철수', 10, 3000, 500);
INSERT INTO EMPLOYEE VALUES (102, '이영희', 20, 2500, NULL);
INSERT INTO EMPLOYEE VALUES (103, '박민수', 10, 1500, 200);
INSERT INTO EMPLOYEE VALUES (104, '정수진', 30, 4000, 800);

-- fetch some values
-- SELECT * FROM EMPLOYEE;
SELECT NAME
FROM EMPLOYEE
WHERE (SALARY > 2000 AND BONUS IS NOT NULL)
OR (DEPT_ID = 20 AND BONUS IS NULL);

-- 결과
-- 김철수, 이영희, 정수진
